-- Migration: Create users, password_resets tables and update customers
-- Description: Add user authentication tables and link customers to users
-- Author: Generated by Sentinel VLA Platform Setup
-- Date: 2025-11-06

BEGIN;

-- ============================================================================
-- CREATE USERS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS vlaapi.users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),

    -- Email verification
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    email_verification_sent_at TIMESTAMP WITH TIME ZONE,

    -- Account status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMP WITH TIME ZONE,

    -- Metadata
    metadata JSONB
);

-- Create indexes for users table
CREATE UNIQUE INDEX idx_users_email ON vlaapi.users(email);
CREATE INDEX idx_users_email_verified ON vlaapi.users(email_verified);
CREATE INDEX idx_users_is_active ON vlaapi.users(is_active);

-- Create updated_at trigger for users
CREATE OR REPLACE FUNCTION vlaapi.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON vlaapi.users
    FOR EACH ROW
    EXECUTE FUNCTION vlaapi.update_updated_at_column();

COMMENT ON TABLE vlaapi.users IS 'User authentication and profile information';
COMMENT ON COLUMN vlaapi.users.user_id IS 'Unique user identifier (UUID)';
COMMENT ON COLUMN vlaapi.users.email IS 'User email address (unique, used for login)';
COMMENT ON COLUMN vlaapi.users.hashed_password IS 'Bcrypt hashed password (never store plaintext!)';

-- ============================================================================
-- CREATE PASSWORD RESETS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS vlaapi.password_resets (
    reset_id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES vlaapi.users(user_id) ON DELETE CASCADE,
    token VARCHAR(255) UNIQUE NOT NULL,

    -- Lifecycle
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for password_resets table
CREATE UNIQUE INDEX idx_password_resets_token ON vlaapi.password_resets(token);
CREATE INDEX idx_password_resets_user ON vlaapi.password_resets(user_id);
CREATE INDEX idx_password_resets_expires ON vlaapi.password_resets(expires_at);
CREATE INDEX idx_password_resets_unused ON vlaapi.password_resets(user_id, expires_at)
    WHERE used_at IS NULL;

COMMENT ON TABLE vlaapi.password_resets IS 'Password reset tokens (expire after 1 hour)';
COMMENT ON COLUMN vlaapi.password_resets.token IS 'Secure random token (URL-safe)';
COMMENT ON COLUMN vlaapi.password_resets.used_at IS 'Timestamp when token was used (NULL if unused)';

-- ============================================================================
-- UPDATE CUSTOMERS TABLE
-- ============================================================================

-- Add user_id foreign key to customers (nullable for backward compatibility)
ALTER TABLE vlaapi.customers
    ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES vlaapi.users(user_id) ON DELETE CASCADE;

-- Add Stripe integration fields
ALTER TABLE vlaapi.customers
    ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS stripe_subscription_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS stripe_subscription_status VARCHAR(50);

-- Create indexes for new customer columns
CREATE INDEX IF NOT EXISTS idx_customers_user_id ON vlaapi.customers(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_stripe_customer_id ON vlaapi.customers(stripe_customer_id)
    WHERE stripe_customer_id IS NOT NULL;

COMMENT ON COLUMN vlaapi.customers.user_id IS 'Link to user authentication (nullable for legacy customers)';
COMMENT ON COLUMN vlaapi.customers.stripe_customer_id IS 'Stripe customer ID for billing';
COMMENT ON COLUMN vlaapi.customers.stripe_subscription_id IS 'Stripe subscription ID';
COMMENT ON COLUMN vlaapi.customers.stripe_subscription_status IS 'Stripe subscription status (active, canceled, past_due, etc.)';

-- ============================================================================
-- GRANTS (Adjust based on your database user)
-- ============================================================================

-- Grant permissions to the application user
GRANT SELECT, INSERT, UPDATE, DELETE ON vlaapi.users TO vlaapi;
GRANT SELECT, INSERT, UPDATE, DELETE ON vlaapi.password_resets TO vlaapi;
GRANT USAGE, SELECT ON SEQUENCE vlaapi.password_resets_reset_id_seq TO vlaapi;

COMMIT;
