#!/bin/bash
# Quick Setup Script for VLA Inference API
# This script helps you get started quickly

set -e  # Exit on error

echo "🤖 VLA Inference API - Quick Setup"
echo "===================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."
echo ""

# Check Python
if command -v python3.10 &> /dev/null; then
    echo "✅ Python 3.10+ found: $(python3.10 --version)"
elif command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
    echo "✅ Python found: $(python3 --version)"
    if (( $(echo "$PYTHON_VERSION < 3.10" | bc -l) )); then
        echo "${YELLOW}⚠️  Python 3.10+ recommended (you have $PYTHON_VERSION)${NC}"
    fi
else
    echo "${RED}❌ Python not found. Please install Python 3.10+${NC}"
    exit 1
fi

# Check Docker
if command -v docker &> /dev/null; then
    echo "✅ Docker found: $(docker --version)"
else
    echo "${YELLOW}⚠️  Docker not found. You'll need to install PostgreSQL and Redis manually${NC}"
fi

# Check GPU (optional)
if command -v nvidia-smi &> /dev/null; then
    echo "✅ NVIDIA GPU detected"
    nvidia-smi --query-gpu=name --format=csv,noheader | head -1
else
    echo "ℹ️  No GPU detected (will use mock models for testing)"
fi

echo ""
read -p "Continue with setup? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

echo ""
echo "🔧 Step 1: Creating Python virtual environment..."
if [ ! -d "venv" ]; then
    if command -v python3.10 &> /dev/null; then
        python3.10 -m venv venv
    else
        python3 -m venv venv
    fi
    echo "✅ Virtual environment created"
else
    echo "ℹ️  Virtual environment already exists"
fi

echo ""
echo "🔧 Step 2: Activating virtual environment..."
source venv/bin/activate
echo "✅ Virtual environment activated"

echo ""
echo "📦 Step 3: Installing Python dependencies..."
echo "   (This may take 2-3 minutes...)"
pip install --upgrade pip > /dev/null 2>&1
pip install -r requirements.txt > /dev/null 2>&1
echo "✅ Dependencies installed"

echo ""
echo "🔧 Step 4: Setting up configuration..."
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo "✅ Created .env file from template"
    else
        # Create minimal .env
        cat > .env << EOF
# VLA Inference API Configuration
# Generated by quick_setup.sh

# Application
ENVIRONMENT=development
DEBUG=true
USE_MOCK_MODELS=true

# API
API_HOST=0.0.0.0
API_PORT=8000

# Database
DATABASE_URL=postgresql+asyncpg://vlaapi:password@localhost:5432/vlaapi

# Redis
REDIS_URL=redis://localhost:6379/0

# Monitoring
ENABLE_PROMETHEUS=true
ENABLE_GPU_MONITORING=false

# Models (for testing with mock models)
ENABLED_MODELS=openvla-7b
DEFAULT_MODEL=openvla-7b
EOF
        echo "✅ Created basic .env file"
    fi
else
    echo "ℹ️  .env file already exists"
fi

echo ""
if command -v docker &> /dev/null; then
    echo "🔧 Step 5: Starting database services..."
    docker-compose up -d postgres redis 2>&1 | grep -v "WARNING"
    
    echo "   Waiting for services to be ready..."
    sleep 5
    
    if docker-compose ps | grep -q "Up"; then
        echo "✅ PostgreSQL and Redis are running"
    else
        echo "${YELLOW}⚠️  Services may not be fully started yet${NC}"
    fi
    
    echo ""
    echo "🔧 Step 6: Initializing database..."
    if [ -f "scripts/setup_database.py" ]; then
        echo "   Creating tables and demo data..."
        # Create minimal setup script if needed
        python scripts/setup_database.py << EOF
y
EOF
        echo "✅ Database initialized"
    else
        echo "${YELLOW}⚠️  setup_database.py not found, skipping${NC}"
    fi
else
    echo "ℹ️  Step 5-6: Docker not available, skipping database setup"
    echo "   You'll need to set up PostgreSQL and Redis manually"
fi

echo ""
echo "======================================"
echo "🎉 Setup Complete!"
echo "======================================"
echo ""
echo "To start the API server, run:"
echo ""
echo "    source venv/bin/activate"
echo "    python -m uvicorn src.api.main:app --port 8000"
echo ""
echo "Then in another terminal, test it:"
echo ""
echo "    python examples/simple_api_test.py"
echo ""
echo "📖 For detailed instructions, see:"
echo "   docs/BEGINNERS_API_GUIDE.md"
echo ""
echo "🌐 Interactive API docs will be at:"
echo "   http://localhost:8000/docs"
echo ""

